### ISSUE TITLE
Add a prepublish transpile

### ISSUE THREAD

**Issue by pward123** [larryprice/novnc-core#2]
Any chance of adding a prepublish transpile?

**Comment by pward123** [comment]
I'm trying to use this in a meteor app and meteor won't transpile node_modules (https://github.com/meteor/meteor-feature-requests/issues/6).

Since you're really not adding anything in your index.js, would you consider changing the 'main' setting in package.json to 'lib/rfb.js'?

Combining the above change with https://github.com/larryprice/novnc-core-autopublish/issues/1 seems to resolve the issues I'm running into

**Comment by larryprice** [comment]
Sorry for the delayed response - I've been on holiday. These are good ideas and I'll look into them.

**Comment by larryprice** [comment]
This part is done. Thanks for the swell idea.
