### ISSUE TITLE
novnc 1.0.0

### ISSUE THREAD

**Issue by LKaemmerling** [larryprice/novnc-core#3]
Hello,

thank you for the type! Have you planed to support the latest release (1.0.0) of the novnc core too?

**Comment by larryprice** [comment]
I'll look into it soon and let you know. I know that the noVNC team was looking into releasing an npm package of their own.

**Comment by larryprice** [comment]
I've updated the package to version 0.2.0 for the latest RFB - take note that the API has changed significantly, I recommend checking out their docs.
