### ISSUE TITLE
no new versions...

### ISSUE THREAD

**Issue by vtolstov** [larryprice/novnc-core#4]
do you have time to run this scheduled weekly?

**Comment by larryprice** [comment]
Yeah, I used to do this and I should be able to set it up again. Last time I tried to use the autopublish script, the transpilation of novnc required a little manual massaging, but I'll bet I could get it back up and running.

**Comment by larryprice** [comment]
OK, published something today and put it in a weekly cronjob. LMK if you have any issues.

**Comment by vtolstov** [comment]
thanks!
